vecadd_naive:	vecadd_naive.upc
				upcc -o $@ $<
vecadd_pri:		vecadd_pri.upc
				upcc -o $@ $<
vecadd_memget:	vecadd_memget.upc
				upcc -o $@ $<

vecadd_naive_dy:	vecadd_naive_dy.upc
					upcc -o $@ $<
vecadd_pri_dy:		vecadd_pri_dy.upc
					upcc -o $@ $<
vecadd_memget_dy:	vecadd_memget_dy.upc
					upcc -o $@ $<
